# Generated by Django 6.0 on 2025-12-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValidationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("csv_file", models.FileField(upload_to="uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_emails", models.IntegerField(default=0)),
                ("processed_emails", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EmailResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "normalized_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("syntax_valid", models.BooleanField(default=False)),
                ("domain_valid", models.BooleanField(default=False)),
                ("is_disposable", models.BooleanField(default=False)),
                ("is_role_based", models.BooleanField(default=False)),
                ("catch_all", models.CharField(default="No", max_length=20)),
                ("domain_age_days", models.IntegerField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=50, null=True)),
                ("smtp_check", models.CharField(default="Unknown", max_length=20)),
                ("has_anti_spam", models.BooleanField(default=False)),
                ("bounce_history", models.BooleanField(default=False)),
                ("rtpc_score", models.IntegerField(default=0)),
                ("status", models.CharField(max_length=20)),
                ("recommendation", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="validator.validationbatch",
                    ),
                ),
            ],
        ),
    ]
