# Generated by Django 6.0 on 2025-12-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0002_disposabledomain_smtpsender_systemconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationbatch",
            name="current_processing_email",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
