# Generated by Django 6.0 on 2025-12-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0005_add_security_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailresult",
            name="firewall_info",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emailresult",
            name="is_asian_region",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailresult",
            name="is_spammy",
            field=models.BooleanField(default=False),
        ),
    ]
