# Generated by Django 6.0 on 2026-01-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0006_emailresult_firewall_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamTrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
